config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "home#index"

  resources :surveys

  resources :questions
  resources :answers
  resources :responses do
    collection { post :import}
  end

  get 'home/about'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :content, presence: true

  belongs_to :question
  has_many :answer_responses

  accepts_nested_attributes_for :answer_responses, allow_destroy: true
end

app/models/answer_response.rb
class AnswerResponse < ActiveRecord::Base
  belongs_to :answer
  belongs_to :response
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :inquiry, presence: true

  belongs_to :survey
  has_many :answers

  accepts_nested_attributes_for :answers, allow_destroy: true

  def self.search_for(query)
    where('id LIKE :query OR survey_id LIKE :query OR inquiry LIKE :query', query: "%#{query}%")
  end

  def self.search_for_survey(query)
    where('survey_id LIKE :query', query: "%#{query}%")
  end
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :survey
  has_many :answer_responses


  accepts_nested_attributes_for :answer_responses, allow_destroy: true

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|

      response = Response.find_or_create_by survey_id: row.to_hash[:survey_id]
      row.to_hash.keys.select { |key| key =~ /question_id/ }.each do |question_column|
        answer_id = row[question_column]
        response.answer_responses.find_or_create_by answer_id: answer_id
      end
    end
  end

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  validates :title, presence: true

  has_many :questions
  has_many :responses
  has_many :answers
  
  accepts_nested_attributes_for :questions, allow_destroy: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def index
    @qanswers = Answer.search_for(params[:q])
  end

  def new
    @answer = Answer.new
  end  

  def create
    @answer = Answer.new(params[:answer])
    if @answer.save
      redirect_to @answer, notice: "Successfully created answer."
    else
      render :new
    end
  end

  def show
    @answer = Answer.find(params[:id])
  end

  def edit
    @answer = Answer.find(params[:id])
  end

  def update
    @answer = Answer.find(params[:id])
    if @answer.update_attributes(answer_params)
      redirect_to @answer, notice: "Successfully updated answer."
    else
      render :edit
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    redirect_to answers_url, notice: "Successfully destroyed answer."
  end

  private

  def answer_params
    params.require(:answer).permit(:content, :question_id, :_destroy)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @questions = Question.search_for_survey(params[:q])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params[:question])
    if @question.save
      redirect_to @question, notice: "Successfully created question."
    else
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(question_params)
      redirect_to @question, notice: "Successfully updated question."
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_url, notice: "Successfully destroyed question."
  end

  private

  def question_params
    params.require(:question).permit(:question_code, :inquiry, answer_attributes: [:content, :_destroy])
  end

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :authenticate_user!

  def index
    @responses = Response.all
  end

  def new
    @response = Response.new
  end

  def create
    @response = Response.new(:response_params)
    if @response.save
      redirect_to @response, notice: "Successfully created response."
    else
      render :new
    end
  end

  def show
    @response = Response.find(params[:id])
  end

  def edit
    @response = Response.find(params[:id])
  end

  def destroy
    @response = Response.find(params[:id])
    @response.destroy
    redirect_to responses_url, notice: "Successfully destroyed response."
  end

  def import
    Response.import(params[:file])
    redirect_to responses_path, notice: "Responses Added Successfully"
  end

  private

    def set_response
      @response = Response.find(params[:id])
    end

    def response_params
      params.require(:response).permit(:respondent_id, :state, :date_of_birth, :race, :gender, :voter_status, :survey_id)
    end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :authenticate_user!

  def index
    @surveys = Survey.all
  end

  def show
    @survey = Survey.find(params[:id])
  end

  def new
    @survey = Survey.new
  end

  def create
    @survey = Survey.new(survey_params)

    if @survey.save
      redirect_to @survey, notice: "Successfully created survey."
    else
      render :new
    end
  end

  def edit
    @survey = Survey.find(params[:id])
  end

  def update
    @survey = Survey.find(params[:id])
    if @survey.update_attributes(survey_params)
      redirect_to @survey, notice: "Successfully updated survey."
    else
      render :edit
    end
  end

  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy
    redirect_to surveys_url, notice: "Successfully destroyed survey."
  end

  private

  def survey_params
    params.require(:survey).permit(:title, :date_published, questions_attributes: [:id, :question_code, :inquiry, :_destroy, answers_attributes: [:id, :content]])
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/home/about.html.erb
<h1>About This Application</h1>

<p>This app was created by Matthew Vilhauer as his final project for General Assembly's Back-End Web Development Course</p>

app/views/home/index.html.erb
<body background="skyline.jpg">
  <div class='jumbotron'>
    <h1 align="center">Welcome to My Survey App</h1>

    <p align="center"><%= link_to "Click here to look at your surveys", surveys_path, class: "btn btn-primary btn-lg", role: "button" %></p>

    <p align="center"><%= link_to "Click here to lookup IDs", questions_path, class: "btn btn-success btn-lg", role: "button" %></p>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MySurveyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to 'MySurveyApp', root_path, class: 'navbar-brand' %>
      </div>
      <div class="collapse navbar-collapse" id="navbar-links">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: 'delete' %></li>
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="content">
    <%= yield %>
  </div>
  <footer class="footer">
    <div class="container">

      <p class="footer_text"><a href="/home/about" class="footer_text">About This App</a> &nbsp/&nbsp  Designed by Matthew Vilhauer</p>

    </div>
  </footer>

</body>

</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :inquiry %><br>
    <%= f.text_field :inquiry %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question <%= @question.id %></h1>

<%= render "form" %>

<br>
<p>
  <%= link_to "Back", @question %> |
  <%= link_to "View All", questions_path %>
</p>

app/views/questions/index.html.erb
<h1><%= link_to "Questions Index", questions_path %></h1>

<p>Enter a Survey ID to Filter Results:</p>
<div class="search">
  <%= form_tag "/questions/", method: "GET" do %>
    <%= text_field_tag :q %>
    <%= submit_tag "Search" %>
  <% end %>
</div>

<div class="article">
  <ol class="questions">
  <% @questions.each do |question| %>
    <li>
      <li>Survey ID: <%= question.survey_id %> || Question ID: <%= question.id %>  ||  <%= question.inquiry %></li>
      <ol class="answers">
        <% question.answers.each do |answer| %>
          <li><%= answer.content %> || ID: <%= answer.id %></li>
        <% end %>
      </ol>
    </li>
  <% end %>
  </ol>
</div>
<br>
<br>
<br>

app/views/questions/new.html.erb
<h1>Questions#new</h1>
<p>Find me in app/views/questions/new.html.erb</p>

app/views/questions/show.html.erb
<h1>Question <%= @question.id %></h1>

<div class="article">
  <ol class="questions">
    <li>
      <li>Survey ID: <%= @question.survey_id %> || Question ID: <%= @question.id %>  ||  <%= @question.inquiry %></li>
      <ol class="answers">
        <% @question.answers.each do |answer| %>
          <li><%= answer.content %> || ID: <%= answer.id %></li>
        <% end %>
      </ol>
    </li>
  </ol>
</div>

<br>
<%= link_to 'Edit Question', edit_question_path %> |
<%= link_to "Delete", @question, :confirm => 'Are you sure?', :method => :delete %> |
<%= link_to 'Back to Questions', questions_path %>

app/views/responses/_form.html.erb
<%= form_for(@response) do |f| %>
  <% if @response.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@response.errors.count, "error") %> prohibited this response from being saved:</h4>

      <ul>
      <% @response.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :survey_id %><br>
    <%= f.number_field :survey_id %>
  </div>
  <div class="field">
    <%= f.label :respondent_id %><br>
    <%= f.number_field :respondent_id %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br>
    <%= f.number_field :date_of_birth %>
  </div>
  <div class="field">
    <%= f.label :race %><br>
    <%= f.text_field :race %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :voter_status %><br>
    <%= f.text_field :voter_status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/responses/edit.html.erb
<h1>Editing Response</h1>

<%= render 'form' %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<h1>Listing All Responses</h1>

<br>
<h4>Import Survey Responses</h4>
<%= form_tag import_responses_path, multipart: true do %>
  <%= file_field_tag :file %>
  <br>
  <%= submit_tag "Import" %>
<% end %>

<br>
<hr>

<table>
  <thead>
    <tr>
      <th class="response_table_header">Survey ID</th>
      <th class="response_table_header">Respondent ID</th>
      <th class="response_table_header">State</th>
      <th class="response_table_header">Year of birth</th>
      <th class="response_table_header">Race</th>
      <th class="response_table_header">Gender</th>
      <th class="response_table_header">Voter Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responses.each do |response| %>
      <tr>
        <td class="response_table_data"><%= response.survey_id %></td>      
        <td class="response_table_data"><%= response.respondent_id %></td>
        <td class="response_table_data"><%= response.state %></td>
        <td class="response_table_data"><%= response.date_of_birth %></td>
        <td class="response_table_data"><%= response.race %></td>
        <td class="response_table_data"><%= response.gender %></td>
        <td class="response_table_data"><%= response.voter_status %></td>
        <td class="response_table_link"><%= link_to 'Show', response %></td>
        <td class="response_table_link"><%= link_to 'Edit', edit_response_path(response) %></td>
        <td class="response_table_link"><%= link_to 'Destroy', response, method: :delete, data: {} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>
<br>

app/views/responses/new.html.erb
<h1>New Response</h1>

<%= render 'form' %>

<%= link_to 'Back', responses_path %>

app/views/responses/show.html.erb
<p>
  <strong>Survey ID:</strong>
  <%= @response.survey_id %>
</p>

<p>
  <strong>Respondent ID:</strong>
  <%= @response.respondent_id %>
</p>

<p>
  <strong>State:</strong>
  <%= @response.state %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @response.date_of_birth %>
</p>

<p>
  <strong>Race:</strong>
  <%= @response.race %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @response.gender %>
</p>

<p>
  <strong>Voter Status:</strong>
  <%= @response.voter_status %>
</p>

<%= link_to 'Edit', edit_response_path(@response) %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/_form.html.erb
<%= nested_form_for @survey do |f| %>
  <% if @survey.errors.any? %>
    <div class="error_messages">
      <h4><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h4>
      <ul>
      <% @survey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h3><%= f.label :title %>
    <%= f.text_field :title %></h3>
  </div>
  
  <br>

  <div class="questions">
    <%= f.fields_for :questions do |question_fields| %>
      <%= question_fields.label :inquiry, "Question" %>
      <%= question_fields.text_area :inquiry %>
      <%= question_fields.link_to_remove "Remove this question" %>

      <p class="answers">
        <%= question_fields.fields_for :answers do |answer_fields| %>
          <%= answer_fields.label :content, "Answer" %>
          <%= answer_fields.text_field :content %>
          <%= answer_fields.link_to_remove "Remove this answer" %>
        <% end %>
        <%= question_fields.link_to_add("Add Answer", :answers) %>
      </p>
      <br>
    <% end %>
    <%= f.link_to_add("Add Question", :questions) %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render "form" %>

<br>
<p>
  <%= link_to "Back", @survey %> |
  <%= link_to "View All", surveys_path %>
</p>
<br>
<br>
<br>

app/views/surveys/index.html.erb
<h1>Surveys</h1>

<% @surveys.each do |survey| %>
  <div class="article">
    <h2><%= link_to survey.title, survey %></h2>
    <%= pluralize(survey.questions.size, "Question") %>
  </div>
<% end %>
<br>
<h3><%= link_to 'New Survey', new_survey_path %></h3>
<br>
<br>
<br>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render "form" %>

<br>
<p><%= link_to "Back to List", surveys_path %></p>
<br>
<br>
<br>

app/views/surveys/show.html.erb
<h1><%= @survey.title %></h1>

<h4>Survey ID: <%= @survey.id %></h4>

<ol class="questions">
  <% @survey.questions.each do |question| %>
    <li><%= question.inquiry %></li>
    <ol class="answers">
      <% question.answers.each do |answer| %>
        <li><%= answer.content %></li>
      <% end %>
    </ol>
  <% end %>
</ol>


<br>
<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to "Destroy", @survey, :confirm => 'Are you sure?', :method => :delete %> |
<%= link_to 'Back to Surveys', surveys_path %>
<br>
<hr>

<h4>Import Survey Responses</h4>
<%= form_tag import_responses_path, multipart: true do %>
  <%= file_field_tag :file %>
  <br>
  <%= submit_tag "Import" %>
<% end %>

<br>
<h3>Survey Responses:</h3>

<table class="responses">
  <tr>
    <th class="response_table_header">Respondent ID</th>
    <th class="response_table_header">State</th>
    <th class="response_table_header">Date of Birth</th>
    <th class="response_table_header">Race</th>
    <th class="response_table_header">Gender</th>
    <th class="response_table_header">Voter Status</th>

  </tr>

  <% @survey.responses.each do |response| %>
    <tr>
      <td class="response_table_data"><%= response.id %></td>
      <td class="response_table_data"><%= response.state %></td>
      <td class="response_table_data"><%= response.date_of_birth %></td>
      <td class="response_table_data"><%= response.race %></td>
      <td class="response_table_data"><%= response.gender %></td>
      <td class="response_table_data"><%= response.voter_status %></td>
    </tr>
  <% end %>
</table>
<br>
<br>
<br>